name: Automatic Versioning
on:
  pull_request:
    types: closed
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - id: bump
        uses: zwaldowski/match-label-action@v2
        with:
          allowed: major,minor,patch
      - uses: zwaldowski/semver-release-action@v2
        with:
          bump: ${{ steps.bump.outputs.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prefix: v
